// <auto-generated />
using DGIIApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DGIIApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608022009_SegundaMigracion")]
    partial class SegundaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("DGIIApp.Models.ComprobanteFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContribuyenteRncCedula")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContribuyenteRncCedula");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("DGIIApp.Models.Contribuyente", b =>
                {
                    b.Property<string>("RncCedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RncCedula");

                    b.ToTable("Contribuyentes");
                });

            modelBuilder.Entity("DGIIApp.Models.ComprobanteFiscal", b =>
                {
                    b.HasOne("DGIIApp.Models.Contribuyente", "Contribuyente")
                        .WithMany("Comprobantes")
                        .HasForeignKey("ContribuyenteRncCedula");

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("DGIIApp.Models.Contribuyente", b =>
                {
                    b.Navigation("Comprobantes");
                });
#pragma warning restore 612, 618
        }
    }
}
